# Climate Indices

Broadscale climate indicators are measures of the temperature, currents, winds, and other factors over long periods of time (six months to decades) in a large, specific geographic region of the ocean. These indices identify naturally occurring variability of the climate, which at this time results in much larger regional changes in conditions than systemic global warming.  Six major climate indicators presented here are the El Niño-Southern Oscillation (Nino4 indexENSO), Multivariate ENSO Index (MEI), Pacific Decadal Oscillation (PDO), East-Pacific-North Pacific teleconnection pattern (EP-NP)North Pacific Index (NPI), Atlantic Multidecadal Oscillation (AMO), and the North Atlantic Oscillation (NAO). Though each of these broadscale climate indicators are based within specific ocean regions and are measured across different time scales, all impact people and ecosystems across the globe and each of the indicators presented here. Interactions between the ocean and atmosphere alters weather around the world and can result in severe storms or mild weather, drought or flooding. Beyond “just” influencing the weather and ocean conditions, these changes can produce secondary results that influence food supplies and prices, forest fires and flooding, and create additional economic and political consequences.

## ENSO
ENSO Data can be downloaded directly from NOAA PSL at this link: https://psl.noaa.gov/data/timeseries/monthly/NINO4/

## MEI
MEI Data can be downloaded directly from NOAA PSL at this link: https://psl.noaa.gov/enso/mei/

## PDO
PDO Data can be downloaded directly from NCDC at this link: https://www.ncdc.noaa.gov/teleconnections/pdo/data.csv

## EPNP
NOAA EPNP Data is hosted by Columbia University at this link: https://iridl.ldeo.columbia.edu/SOURCES/.NOAA/.NCEP/.CPC/.Indices/.NHTI/EPNP/T+exch+table-+text+text+skipanyNaN+-table+.html

## NAO
NAO Data can be downloaded directly from NCDC at this link: https://www.ncdc.noaa.gov/teleconnections/nao/data.csv

## AMO
AMO Data can be downloaded directly from NOAA PSL at this link: https://www.esrl.noaa.gov/psd/data/timeseries/AMO/

Questions can be directed to willem.klajbor@noaa.gov or scott.cross@noaa.gov
